### ISSUE TITLE
visualization.py cp949 codec error

### ISSUE THREAD

**Issue by seogihyun** [NVlabs/stylegan3#14] opened 2021-10-13 06:47 UTC
**Describe the bug**
```
Traceback (most recent call last):
  File "C:\Users\82109\Desktop\stylegan3\viz\renderer.py", line 136, in render
    self._render_impl(res, **args)
  File "C:\Users\82109\Desktop\stylegan3\viz\renderer.py", line 278, in _render_impl
    all_ws = G.mapping(z=all_zs, c=all_cs, truncation_psi=trunc_psi, truncation_cutoff=trunc_cutoff) - w_avg
  File "C:\Users\82109\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 238, in forward
  File "C:\Users\82109\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 116, in forward
  File "C:\Users\82109\Desktop\stylegan3\torch_utils\ops\bias_act.py", line 84, in bias_act
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
  File "C:\Users\82109\Desktop\stylegan3\torch_utils\ops\bias_act.py", line 46, in _init
    extra_cuda_cflags=['--use_fast_math'],
  File "C:\Users\82109\Desktop\stylegan3\torch_utils\custom_ops.py", line 137, in get_plugin
    verbose=verbose_build, sources=cached_sources, **build_kwargs)
  File "C:\Users\82109\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1091, in load
    keep_intermediates=keep_intermediates)
  File "C:\Users\82109\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1269, in _jit_compile
    is_standalone=is_standalone,
  File "C:\Users\82109\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\_cpp_extension_versioner.py", line 16, in hash_source_files
    hash_value = update_hash(hash_value, file.read())
UnicodeDecodeError: 'cp949' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
```

**To Reproduce**
1. Run visualization.py
2. click recent
3. any pickle download 
4. show this error

**Expected behavior**

**Screenshots**
![캡처](https://user-images.githubusercontent.com/72849922/137081208-ad48c8f7-e286-46fa-9b2d-8935eb31c44e.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - torch 1.8.1+cu111
 - GPU [RTX 3090]

**Comment by nurpax** [comment] 2021-10-13 09:18
This is probably a duplicate of https://github.com/NVlabs/stylegan3/issues/10.

I will be fixing this today by removing all UTF-8 BOM markers from the StyleGAN3 source files.

**Closed as completed** 2021-10-13 10:26 UTC
